name: Set Production Deployment URL

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  deployments: write
  contents: read

jobs:
  production:
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://college-gpt-seven.vercel.app/

    steps:
      - name: Production deployment URL
        run: echo "Production URL: https://college-gpt-seven.vercel.app/"
